services:
  postgres:
    image: postgres:16-alpine
    container_name: english-web-db
    environment:
      POSTGRES_DB: english_web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/db_v1.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d english_web"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
